[
    {
        _id: 1,
        imageURL: "",
        company: "Marvel",
        name: "Iron Man",
        civName: "Tony Stark",
        alignment: "Hero",
        firstDebut: "Tales of Suspense #39 (March 1963)",
        abilities: ["Genius-level intellect", "Proficient scientist and engineer", "Powered armor suit"],
        teams: ["Avengers", "New Avengers", "Guardians of the Galaxy", "Illuminati", "Thunderbolts"],
        desc: "After being held captive in a foreign country by terrorists, genius industrialist Tony Stark creates a suit of powered armor equipped with weapons, super strength and supersonic speed. He continues to serve the public as Iron Man, the armored Avenger."
    },
    {
        _id: 2,
        imageURL: "",
        company: "Marvel",
        name: "Captain America",
        civName: "Steven Rogers",
        alignment: "Hero",
        firstDebut: "Captain America Comics #1 (March 1941)",
        abilities: ["Peak Human Ability", "Master martial artist", "Tactical Expertise", "Vibranium Shield"],
        teams: ["All-Winners Squad", "Avengers", "New Avengers", "Secret Avengers", "Invaders", "Illuminati"],
        desc: "Disturbed by Adolf Hitler's rise to power, Steven Rogers attempts to enlist but was rejected due to his frail body. Rogers was used as a test subject for the Super-Soldier project, receiving a special serum made by scientist Abraham Erskine. While fighting against Hydra in World War 2, he was frozen in ice until revived by S.H.I.E.L.D. in modern times."
    },
    {
        _id: 3,
        imageURL: "",
        company: "Marvel",
        name: "Thor",
        civName: "Thor Odinson",
        alignment: "Hero",
        firstDebut: "Journey into Mystery #83 (August 1962)",
        abilities: ["Superhuman strength, speed, durability and longevity", "Mjolnir"],
        teams: ["Avengers", "Warriors Three", "Thor Corps", "God Squad", "Avengers Unity Squad"],
        desc: "Thor hails from Asgard as the Norse God of Thunder. He is the son of Odin and the brother of Loki. His hammer, Mjolnir grants him incredible powers such as flight, dimensional transportation and controlling lightning."
    },
    {
        _id: 4,
        imageURL: "",
        company: "Marvel",
        name: "Hulk",
        civName: "Bruce Banner",
        alignment: "Hero",
        firstDebut: "The Incredible Hulk #1 (May 1962)",
        abilities: ["Invulnerability", "Superhuman strength, stamina and durability"],
        teams: ["Avengers", "Defenders", "Horsemen of the Apocalypse", "Fantastic Four", "Pantheon", "Warbound"],
        desc: "During the experimental detonation of a gamma bomb, scientist Robert Bruce Banner absorbs massive amounts of gamma radiation. This triggered his ability to transform into a lumbering green monster when angered. One time he was shot into space and became a gladiator."
    },
    {
        _id: 5,
        imageURL: "",
        company: "Marvel",
        name: "Black Panther",
        civName: "T'Challa",
        alignment: "Hero",
        firstDebut: "Fantastic Four #52 (July 1966)",
        abilities: ["Enhanced strength, speed, durability, and senses", "Master martial artist", "Genius-level intellect", "Tactical expertise", "Vibranium suit"],
        teams: ["Avengers", "Fantastic Force", "Fantastic Four", "Ultimates"],
        desc: "T'Challa is the King of the African country of Wakanda. Upon rising to the throne and consuming the heart-shaped herb, he inherited the power of every previous Black Panther. With his vibranium suit, nothing can stop him from defending his people."
    },
    {
        _id: 6,
        imageURL: "",
        company: "Marvel",
        name: "Spider-Man",
        civName: "Peter Parker",
        alignment: "Hero",
        firstDebut: "Amazing Fantasy #15 (August 1962)",
        abilities: ["Genius-level intellect", "Proficient scientist and inventor", "Superhuman strength, speed, durability, and agility", "Ability to cling to most surfaces", "precognition", "web-shooters"],
        teams: ["Avengers", "Fantastic Four", "New Avengers"],
        desc: "After being bitten by a radioactive spider, Peter Parker developed the ability to climb walls and utilize spider-sense. failing to prevent the death of Uncle Ben, he now lives by the motto 'With great power comes great responsibility'."
    },
    {
        _id: 7,
        imageURL: "",
        company: "Marvel",
        name: "Human Torch",
        civName: "Johnny Storm",
        alignment: "Hero",
        firstDebut: "The Fantastic Four #1 (Nov. 1961)",
        abilities: ["Pyrokinesis", "Fiery form, serves as damage shield", "Heat energy absorption", "Resistance to extreme heat"],
        teams: ["Fantastic Four", "Fantastic Force", "Herald of Galactus"],
        desc: "Johnny Storm developed the ability to turn to flame and fly after being exposed to cosmic radiation. He is one of the iconic members of Fantastic Four. Flame on!"
    },
    {
        _id: 8,
        imageURL: "",
        company: "Marvel",
        name: "Wolverine",
        civName: "James Howlett",
        alignment: "Antihero",
        firstDebut: "The Incredible Hulk #180 (October 1974)",
        abilities: ["Superhuman senses, agility, reflexes, and animal-like attributes", "Extended longevity via regenerative healing factor", "Adamantium-plated skeleton", "Retractable bone claws", "Master martial artist"],
        teams: ["Alpha Flight", "Avengers", "New Fantastic Four", "X-Men", "X-Force"],
        desc: "Wolverine made his debut hunting the Hulk for the canadian government. since then he's become the most famous member of the X-Men with his adamantium claws, healing factor, and no-nonsense attitude. You wouldn't like him when he's angry."
    },
    {
        _id: 9,
        imageURL: "",
        company: "Marvel",
        name: "Cyclops",
        civName: "Scott Summers",
        alignment: "Hero",
        firstDebut: "The X-Men #1 (Sep. 1963)",
        abilities: ["Optic blasts", "Advanced spatial awareness", "Tactical expertise"],
        teams: ["X-Men", "X-Force", "X-Factor", "Phoenix Five", "Champions"],
        desc: "Cyclops is the leader of the X-men. He's well-known for his optic blasts and relationship with Jean Grey. A lot of people think he's boring though."
    },
    {
        _id: 10,
        imageURL: "",
        company: "Marvel",
        name: "Squirrel Girl",
        civName: "Doreen Allene Green",
        alignment: "Hero",
        firstDebut: "Marvel Super-Heroes vol. 2 #8 (Winter 1991)",
        abilities: ["Superhuman agility, senses, and strength", "Prehensile tail", "Razor-sharp claws", "Retractable knuckle spikes", "Ability to communicate with squirrels"],
        teams: ["Great Lake Avengers", "U.S. Avengers"],
        desc: "Squirrel Girl is one of the most powerful entities in the Marvel Universe. Thanos, Dr. Doom, and Fin Fang Foom all have fallen to her squirrely might. Her power is such that she left the Great Lakes Avengers because she felt she was holding them back."
    },
    {
        _id: 11,
        imageURL: "",
        company: "Marvel",
        name: "Thanos",
        civName: "Thanos",
        alignment: "Villain",
        firstDebut: "The Invincible Iron Man #55 (February 1973)",
        abilities: ["Superhuman strength, speed, agility, durability, and longevity", "Superhuman physiology of Eternals", "Tactical expertise", "Master martial artist", "Plasma projection"],
        teams: ["Black Order", "Infinity Watch"],
        desc: "The Mad Titan himself. Thanos is the last of a dead race, and infamously assembled the infinity gauntlet, using all six infinity gems to erase half the life in the universe so he could court death. He is one of the Avenger's greatest enemies."
    },
    {
        _id: 12,
        imageURL: "",
        company: "Marvel",
        name: "Doctor Doom",
        civName: "Victor Von Doom",
        alignment: "Villain",
        firstDebut: "The Fantastic Four #5 (July 1962)",
        abilities: ["Genius-level intellect", "Skilled sorcerer", "Mystical energy projection and absorption", "Mind transference", "Powered armor"],
        teams: ["Sorcerers Supreme", "The Cabal", "Intelligencia", "Lethal Legion"],
        desc: "Doctor Doom rules Latveria with an iron fist. He is a talented occultist and sinister genius. Those who hear of him find his title to be eloquent in its simplicity — magnificent in its implied menace."
    },
    {
        _id: 13,
        imageURL: "",
        company: "Marvel",
        name: "Magneto",
        civName: "Max Eisenhardt",
        alignment: "Villain",
        firstDebut: "The X-Men #1 (Sept. 1963)",
        abilities: ["Magnetism manipulation and generation of magnetic force fields", "Flight through magnetic fields", "Helmet shields against telepathic attacks"],
        teams: ["Brotherhood of Evil Mutants", "Hellfire Club", "X-Men"],
        desc: "The power to control all metals makes Magneto one of the most dangerous mutants in the world. While a friend of Charles Xavier, his differing view on the identity politics of mutantkind routinely pushes their relationship to the limits. Magneto is also the father of Scarlet Witch and Quicksilver."
    },
    {
        _id: 14,
        imageURL: "",
        company: "Marvel",
        name: "Red Skull",
        civName: "Johann Schmidt",
        alignment: "Villain",
        firstDebut: "Captain America Comics #7 (October 1941)",
        abilities: ["Genius-level intellect", "Tactical expertist", "Martial arts master", "Skilled marksman", "Inhabits a cloned body of Captain America."],
        teams: ["HYDRA", "AIM", "ULTIMATUM", "Skeleton Crew"],
        desc: "Johann Schmidt was a Nazi general officer and confidant of Adolf Hitler. He has been closely affiliated with Hydra and is an enemy of S.H.I.E.L.D., the Avengers, and the interests of the United States and the free world in general. He has been seemingly killed in the past, only to return time and time again to plague the world with schemes of world domination and genocide."
    },
    {
        _id: 15,
        imageURL: "",
        company: "Marvel",
        name: "Loki",
        civName: "Loki Laufeyson",
        alignment: "Antihero",
        firstDebut: "Journey into Mystery #85 (October 1962)",
        abilities: ["Master of manipulation and deceit", "Superhuman strength, speed, durability, and longevity", "Shapeshifting", "Illusion casting", "Teleportation."],
        teams: ["Acts of Vengeance", "Astonishing Avengers", "Cabal", "Young Avengers"],
        desc: "He is the adopted brother and often the enemy of the superhero Thor. Loki is based on the Norse deity of the same name and is sometimes depicted as an antihero. As the god of mischief, he'll always have a trick up his sleeve."
    },
    {
        _id: 16,
        imageURL: "",
        company: "Marvel",
        name: "Doctor Octopus",
        civName: "Otto Gunther Octavius",
        alignment: "Villain",
        firstDebut: "The Amazing Spider-Man #3 (July 1963)",
        abilities: ["Brilliant engineer and inventor", "Genius-level intellect", "Tactical expertise", "super-strong and durable mechanical appendages"],
        teams: ["Sinister Six", "Masters of Evil", "Thunderbolts", "Legion Accursed"],
        desc: "A highly intelligent mad scientist, Doctor Octopus is a stocky, myopic man who utilizes four powerful, mechanical appendages, and is obsessed with proving his own genius and destroying the superhero Spider-Man. During an accidental radiation leak that ended in an explosion, the four arms became fused to Otto Octavius's body. Though Doctor Octopus himself is in poor physical shape, and is near-sighted, with his harness attached he is physically more than a match for the web-slinger."
    },
    {
        _id: 17,
        imageURL: "",
        company: "Marvel",
        name: "Kingpin",
        civName: "Wilson Fisk",
        alignment: "Villain",
        firstDebut: "The Amazing Spider-Man #50 (July 1967)",
        abilities: ["Master martial artist", "Criminal mastermind", "Peak-level strength and durability", "Use of a laser gun-equipped cane and a hollow-on-the-inside ornamental diamond stick-pin filled with sleeping gas"],
        teams: ["HYRDRA", "The Hand", "Emissaries of Evil"],
        desc: "Wilson Fisk rose from obscurity to become one of the most powerful crime lords in the world. His money and resources make him untouchable to politicians and law enforcement, while his army of hired thugs and assassins makes it all but impossible to topple his regime. When even heroes like Spider-Man and Daredevil have failed to defeat Fisk, you know he’s a force to be reckoned with."
    },
    {
        _id: 18,
        imageURL: "",
        company: "Marvel",
        name: "Galactus",
        civName: "Galan",
        alignment: "Villain",
        firstDebut: "Fantastic Four #48 (March 1966)",
        abilities: ["The Power Cosmic"],
        teams: ["Heralds of Galactus", "God Squad", "Ultimates"],
        desc: "For Marvel’s heroes, threats don’t come bigger or more dire than Galactus. Earth has been on his menu several times, and only through desperate actions and out-of-the-box thinking have heroes like the Fantastic Four been able to drive him away. Sooner or later, his hunger will prevail."
    },
    {
        _id: 19,
        imageURL: "",
        company: "Marvel",
        name: "The Punisher",
        civName: "Frank Castle",
        alignment: "Antihero",
        firstDebut: "The Amazing Spider-Man #129 (February 1974)",
        abilities: ["Skilled in guerrilla and military tactics, close quarters combat, infiltration, marksmanship, and demolitions", "Special operations training"],
        teams: ["Heroes for Hire", "Secret Defenders", "Thunderbolts"],
        desc: "The Punisher is a vigilante who employs murder, kidnapping, extortion, coercion, threats of violence, and torture in his campaign against crime. Driven by the deaths of his wife and two children who were killed by the mob for witnessing a killing in New York City's Central Park, he wages a one-man war on the mob and all violent criminals in general while employing the use of various firearms. A war veteran and a United States Marine Corps Scout Sniper, Castle is skilled in hand-to-hand combat, guerrilla warfare, and marksmanship."
    },
    {
        _id: 20,
        imageURL: "",
        company: "Marvel",
        name: "Deadpool",
        civName: "Wade Wilson",
        alignment: "Antihero",
        firstDebut: "The New Mutants #98 (February 1991)",
        abilities: ["Healing factor", "Master martial artist", "devices granting teleportation and holographic disguise", "awareness of the fourth wall"],
        teams: ["Astonishing Avengers", "Deadpool Corps", "Frightful Four", "Great Lakes Avengers", "Heroes for Hire", "Mercs for Money", "Secret Defenders", "Six Pack", "Thunderbolts", "X-Force", "X-Men"],
        desc: "It's me, Deadpool! I've got cool swords and guns and I'm breaking the fourth wall right now! I've even got two blockbuster movies!"
    }

];